import React, { useState, useEffect } from 'react';
import {
  Check,
  Calendar,
  Building2,
  FileText,
  Ruler,
  Users,
} from 'lucide-react';
import { createSite, CreateSiteData, SiteFrontend } from '../../services/api';
import { fetchClients } from '../../services/usersApi';
import { Client } from '../../types/users';
import { useToast } from '../../contexts/ToastContext';
import { GeometryMetrics } from '../../types';
import { FormModal } from '../FormModal';

interface CreateSiteModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (site: SiteFrontend) => void;
  geometry: { type: string; coordinates: number[][][] } | null;
  metrics: GeometryMetrics | null;
}

export const CreateSiteModal: React.FC<CreateSiteModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  geometry,
  metrics,
}) => {
  const { showToast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Clients state
  const [clients, setClients] = useState<Client[]>([]);
  const [isLoadingClients, setIsLoadingClients] = useState(false);

  // Form fields
  const [nomSite, setNomSite] = useState('');
  const [clientId, setClientId] = useState<number | ''>('');
  const [adresse, setAdresse] = useState('');
  const [superficieTotale, setSuperficieTotale] = useState<string>('');
  const [dateDebutContrat, setDateDebutContrat] = useState('');
  const [dateFinContrat, setDateFinContrat] = useState('');
  const [actif, setActif] = useState(true);

  // Fetch clients on mount
  useEffect(() => {
    const loadClients = async () => {
      setIsLoadingClients(true);
      try {
        const response = await fetchClients();
        // Filter only active clients
        const activeClients = (response.results || []).filter(c => c.actif);
        setClients(activeClients);
      } catch (error) {
        console.error('Error loading clients:', error);
        showToast('Erreur lors du chargement des clients', 'error');
      } finally {
        setIsLoadingClients(false);
      }
    };

    if (isOpen) {
      loadClients();
    }
  }, [isOpen, showToast]);

  // Reset form when modal opens
  useEffect(() => {
    if (isOpen) {
      setNomSite('');
      setClientId('');
      setAdresse('');
      setDateDebutContrat('');
      setDateFinContrat('');
      setActif(true);
      setError(null);
    }
  }, [isOpen]);

  // Update superficie from calculated metrics
  useEffect(() => {
    if (metrics?.area_m2) {
      const areaInHa = (metrics.area_m2 / 10000).toFixed(4);
      setSuperficieTotale(areaInHa);
    }
  }, [metrics]);

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!geometry || geometry.type !== 'Polygon') {
      setError('Erreur: géométrie invalide');
      return;
    }

    if (!nomSite.trim()) {
      setError('Le nom du site est obligatoire');
      return;
    }

    if (!clientId) {
      setError('Le client est obligatoire');
      return;
    }

    setIsSubmitting(true);
    setError(null);

    try {
      const siteData: CreateSiteData = {
        nom_site: nomSite.trim(),
        client: clientId as number,
        // code_site is auto-generated by the backend
        adresse: adresse.trim() || undefined,
        superficie_totale: superficieTotale ? parseFloat(superficieTotale) : undefined,
        date_debut_contrat: dateDebutContrat || undefined,
        date_fin_contrat: dateFinContrat || undefined,
        actif,
        geometrie_emprise: geometry as { type: 'Polygon'; coordinates: number[][][] },
      };

      const newSite = await createSite(siteData);
      showToast(`Site "${nomSite}" créé avec succès!`, 'success');
      onSuccess(newSite);
      onClose();
    } catch (error: any) {
      console.error('Erreur création site:', error);
      setError(error.message || 'Erreur lors de la création du site');
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <FormModal
      isOpen={isOpen}
      onClose={onClose}
      onSubmit={handleSubmit}
      title="Nouveau site"
      subtitle="Renseignez les informations du site"
      icon={<Building2 className="w-5 h-5" />}
      size="lg"
      loading={isSubmitting}
      error={error}
      submitLabel={isSubmitting ? 'Création...' : 'Créer le site'}
      submitVariant="primary"
      cancelLabel="Annuler"
    >
      {/* Geometry Info */}
      {metrics && (
        <div className="px-4 py-3 bg-emerald-50 border border-emerald-200 rounded-lg flex items-center gap-4 text-sm text-emerald-700 -mt-2 mb-4">
          <span className="flex items-center gap-1.5">
            <Ruler className="w-4 h-4" />
            {(metrics.area_m2! / 10000).toFixed(2)} ha
          </span>
          <span className="flex items-center gap-1.5">
            <Ruler className="w-4 h-4" />
            {(metrics.perimeter_m! / 1000).toFixed(2)} km de périmètre
          </span>
        </div>
      )}

      <div className="space-y-4">
        {/* Client (Required) */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">
            <div className="flex items-center gap-2">
              <Users className="w-4 h-4 text-gray-400" />
              Client <span className="text-red-500">*</span>
            </div>
          </label>
          {isLoadingClients ? (
            <div className="flex items-center gap-2 text-gray-500 text-sm py-2">
              <div className="w-4 h-4 border-2 border-gray-300 border-t-emerald-600 rounded-full animate-spin" />
              Chargement des clients...
            </div>
          ) : (
            <select
              value={clientId}
              onChange={(e) => setClientId(e.target.value ? parseInt(e.target.value) : '')}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition-colors"
              required
            >
              <option value="">-- Sélectionner un client --</option>
              {clients.map((client) => (
                <option key={client.utilisateur} value={client.utilisateur}>
                  {client.nomStructure} ({client.nom} {client.prenom})
                </option>
              ))}
            </select>
          )}
        </div>

        {/* Nom du site */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">
            <div className="flex items-center gap-2">
              <Building2 className="w-4 h-4 text-gray-400" />
              Nom du site <span className="text-red-500">*</span>
            </div>
          </label>
          <input
            type="text"
            value={nomSite}
            onChange={(e) => setNomSite(e.target.value)}
            placeholder="Ex: Hilton Garden Inn"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition-colors"
            required
          />
        </div>

        {/* Adresse */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">
            <div className="flex items-center gap-2">
              <FileText className="w-4 h-4 text-gray-400" />
              Adresse
            </div>
          </label>
          <input
            type="text"
            value={adresse}
            onChange={(e) => setAdresse(e.target.value)}
            placeholder="Ex: 123 Avenue Mohammed V, Casablanca"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition-colors"
          />
        </div>

        {/* Superficie */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1.5">
            <div className="flex items-center gap-2">
              <Ruler className="w-4 h-4 text-gray-400" />
              Superficie (ha)
            </div>
          </label>
          <input
            type="number"
            step="0.0001"
            value={superficieTotale}
            onChange={(e) => setSuperficieTotale(e.target.value)}
            placeholder="Calculée automatiquement"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent bg-gray-50 transition-colors"
            readOnly
          />
        </div>

        {/* Dates */}
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4 text-gray-400" />
                Début contrat
              </div>
            </label>
            <input
              type="date"
              value={dateDebutContrat}
              onChange={(e) => setDateDebutContrat(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition-colors"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4 text-gray-400" />
                Fin contrat
              </div>
            </label>
            <input
              type="date"
              value={dateFinContrat}
              onChange={(e) => setDateFinContrat(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition-colors"
            />
          </div>
        </div>

        {/* Actif */}
        <div className="flex items-center gap-3 pt-2">
          <input
            type="checkbox"
            id="actif"
            checked={actif}
            onChange={(e) => setActif(e.target.checked)}
            className="w-4 h-4 text-emerald-600 border-gray-300 rounded focus:ring-emerald-500"
          />
          <label htmlFor="actif" className="text-sm text-gray-700 font-medium">
            Site actif
          </label>
        </div>
      </div>
    </FormModal>
  );
};

export default CreateSiteModal;
