import React, { useState, useEffect } from 'react';
import { Calendar, Building2, Ruler, Users, MapPin, Power, Loader2 } from 'lucide-react';
import { createSite, CreateSiteData, SiteFrontend } from '../../services/api';
import { fetchStructures } from '../../services/usersApi';
import { StructureClient } from '../../types/users';
import { useToast } from '../../contexts/ToastContext';
import { GeometryMetrics, GeoJSONGeometry } from '../../types';
import FormModal, { FormSection, FormGrid } from '../FormModal';
import { PremiumInput, PremiumSelect } from '../modals/PremiumFormComponents';

interface CreateSiteModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (site: SiteFrontend) => void;
  /**
   * Géométrie dessinée sur la carte. Seul un `Polygon` est accepté à la
   * soumission (cf. validation en dessous) — mais on accepte le type large
   * pour coller au `drawnGeometry` du contexte.
   */
  geometry: GeoJSONGeometry | null;
  metrics: GeometryMetrics | null;
}

export const CreateSiteModal: React.FC<CreateSiteModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  geometry,
  metrics,
}) => {
  const { showToast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Clients state
  const [clients, setClients] = useState<StructureClient[]>([]);
  const [isLoadingClients, setIsLoadingClients] = useState(false);

  // Form data
  const [formData, setFormData] = useState({
    nom_site: '',
    structure_client: null as number | null,
    adresse: '',
    superficie_totale: '',
    date_debut_contrat: '',
    date_fin_contrat: '',
    actif: true,
  });

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  // Fetch clients on mount
  useEffect(() => {
    const loadClients = async () => {
      setIsLoadingClients(true);
      try {
        const response = await fetchStructures();
        // Filter only active structures
        const activeClients = (response.results || []).filter((c) => c.actif);
        setClients(activeClients);
      } catch (error) {
        showToast('Erreur lors du chargement des clients', 'error');
      } finally {
        setIsLoadingClients(false);
      }
    };

    if (isOpen) {
      loadClients();
    }
  }, [isOpen, showToast]);

  // Reset form when modal opens
  useEffect(() => {
    if (isOpen) {
      setFormData({
        nom_site: '',
        structure_client: null,
        adresse: '',
        superficie_totale: '',
        date_debut_contrat: '',
        date_fin_contrat: '',
        actif: true,
      });
      setError(null);
    }
  }, [isOpen]);

  // Update superficie from calculated metrics
  useEffect(() => {
    if (metrics?.area_m2) {
      const areaInHa = (metrics.area_m2 / 10000).toFixed(4);
      handleChange('superficie_totale', areaInHa);
    }
  }, [metrics]);

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!geometry || geometry.type !== 'Polygon') {
      setError('Erreur: géométrie invalide');
      return;
    }

    if (!formData.nom_site.trim()) {
      setError('Le nom du site est obligatoire');
      return;
    }

    if (!formData.structure_client) {
      setError('Le client est obligatoire');
      return;
    }

    setIsSubmitting(true);
    setError(null);

    try {
      const siteData: CreateSiteData = {
        nom_site: formData.nom_site.trim(),
        structure_client: formData.structure_client!,
        // code_site is auto-generated by the backend
        adresse: formData.adresse.trim() || undefined,
        superficie_totale: formData.superficie_totale
          ? parseFloat(formData.superficie_totale)
          : undefined,
        date_debut_contrat: formData.date_debut_contrat || undefined,
        date_fin_contrat: formData.date_fin_contrat || undefined,
        actif: formData.actif,
        geometrie_emprise: geometry as { type: 'Polygon'; coordinates: number[][][] },
      };

      const newSite = await createSite(siteData);
      showToast(`Site "${formData.nom_site}" créé avec succès!`, 'success');
      onSuccess(newSite);
      onClose();
    } catch (error: any) {
      const errorMessage = error.message || 'Erreur lors de la création du site';
      setError(errorMessage);
      showToast(errorMessage, 'error');
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isOpen) return null;

  // Préparer les options du select client
  const clientOptions = clients.map((client) => ({
    value: client.id.toString(),
    label: client.nom,
  }));

  return (
    <FormModal
      isOpen={isOpen}
      onClose={onClose}
      onSubmit={handleSubmit}
      title="Nouveau site"
      subtitle="Tracez un polygone sur la carte puis renseignez les informations"
      icon={<Building2 className="w-5 h-5 text-emerald-600" />}
      size="lg"
      loading={isSubmitting}
      error={error}
      submitLabel={isSubmitting ? 'Création...' : 'Créer le site'}
      cancelLabel="Annuler"
      useGradientHeader={true}
    >
      {/* Geometry Info */}
      {metrics && (
        <div className="px-4 py-3 bg-emerald-50 border border-emerald-200 rounded-lg flex items-center gap-4 text-sm font-medium text-emerald-700 mb-4">
          <span className="flex items-center gap-1.5">
            <Ruler className="w-4 h-4" />
            Superficie: {(metrics.area_m2! / 10000).toFixed(2)} ha
          </span>
          <span className="flex items-center gap-1.5">
            <MapPin className="w-4 h-4" />
            Périmètre: {(metrics.perimeter_m! / 1000).toFixed(2)} km
          </span>
        </div>
      )}

      {/* Section Informations principales */}
      <FormSection title="Informations principales" description="Identité et localisation du site">
        <FormGrid columns={1}>
          {isLoadingClients ? (
            <div className="flex items-center gap-2 text-sm text-slate-500 py-3 px-3 bg-slate-50 rounded-lg border border-slate-200">
              <Loader2 className="w-4 h-4 animate-spin text-emerald-600" />
              Chargement des clients...
            </div>
          ) : (
            <PremiumSelect
              value={formData.structure_client?.toString() || ''}
              onChange={(value) => handleChange('structure_client', value ? parseInt(value) : null)}
              options={clientOptions}
              label="Client propriétaire"
              placeholder="Sélectionner un client"
              icon={<Users className="w-4 h-4" />}
              disabled={isSubmitting}
              required
              variant="outlined"
              size="md"
            />
          )}
        </FormGrid>

        <FormGrid columns={2}>
          <PremiumInput
            type="text"
            value={formData.nom_site}
            onChange={(value) => handleChange('nom_site', value)}
            label="Nom du site"
            placeholder="Ex: Hilton Garden Inn"
            icon={<Building2 className="w-4 h-4" />}
            disabled={isSubmitting}
            required
            variant="outlined"
            size="md"
          />

          <PremiumInput
            type="number"
            value={formData.superficie_totale}
            onChange={(value) => handleChange('superficie_totale', value)}
            label="Superficie (ha)"
            placeholder="Calculée automatiquement"
            icon={<Ruler className="w-4 h-4" />}
            disabled={true}
            variant="outlined"
            size="md"
            hint="Calculée depuis la géométrie tracée"
          />
        </FormGrid>

        <FormGrid columns={1}>
          <PremiumInput
            type="text"
            value={formData.adresse}
            onChange={(value) => handleChange('adresse', value)}
            label="Adresse"
            placeholder="Ex: 123 Avenue Mohammed V, Casablanca"
            icon={<MapPin className="w-4 h-4" />}
            disabled={isSubmitting}
            variant="outlined"
            size="md"
          />
        </FormGrid>
      </FormSection>

      {/* Section Période contractuelle */}
      <FormSection
        title="Période contractuelle"
        description="Dates de début et fin du contrat de maintenance"
      >
        <FormGrid columns={2}>
          <PremiumInput
            type="date"
            value={formData.date_debut_contrat}
            onChange={(value) => handleChange('date_debut_contrat', value)}
            label="Date de début"
            icon={<Calendar className="w-4 h-4" />}
            disabled={isSubmitting}
            variant="outlined"
            size="md"
          />

          <PremiumInput
            type="date"
            value={formData.date_fin_contrat}
            onChange={(value) => handleChange('date_fin_contrat', value)}
            label="Date de fin"
            icon={<Calendar className="w-4 h-4" />}
            disabled={isSubmitting}
            variant="outlined"
            size="md"
          />
        </FormGrid>
      </FormSection>

      {/* Section Statut */}
      <FormSection title="Statut" description="Activation ou désactivation du site">
        <div
          className={`flex items-center justify-between p-4 rounded-xl border-2 transition-all cursor-pointer ${
            formData.actif
              ? 'bg-emerald-50 border-emerald-200 hover:border-emerald-300'
              : 'bg-slate-50 border-slate-200 hover:border-slate-300'
          }`}
          onClick={() => !isSubmitting && handleChange('actif', !formData.actif)}
        >
          <div className="flex items-center gap-4">
            <div
              className={`w-12 h-12 rounded-xl flex items-center justify-center transition-colors ${
                formData.actif ? 'bg-emerald-100' : 'bg-slate-200'
              }`}
            >
              <Power
                className={`w-6 h-6 ${formData.actif ? 'text-emerald-600' : 'text-slate-400'}`}
              />
            </div>
            <div>
              <p
                className={`font-semibold ${formData.actif ? 'text-emerald-900' : 'text-slate-700'}`}
              >
                {formData.actif ? 'Site actif' : 'Site inactif'}
              </p>
              <p className="text-sm text-slate-500">
                {formData.actif
                  ? 'Le site est visible et disponible pour les opérations'
                  : 'Le site est masqué et non disponible pour les opérations'}
              </p>
            </div>
          </div>

          {/* Toggle Switch */}
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              if (!isSubmitting) handleChange('actif', !formData.actif);
            }}
            disabled={isSubmitting}
            className={`relative inline-flex h-7 w-12 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed ${
              formData.actif
                ? 'bg-emerald-500 focus:ring-emerald-500'
                : 'bg-slate-300 focus:ring-slate-500'
            }`}
          >
            <span
              className={`inline-block h-5 w-5 transform rounded-full bg-white shadow-lg transition-transform ${
                formData.actif ? 'translate-x-6' : 'translate-x-1'
              }`}
            />
          </button>
        </div>
      </FormSection>
    </FormModal>
  );
};

export default CreateSiteModal;
